### ISSUE TITLE
打包 minist_summary.py 报错

### ISSUE THREAD

**Issue by LMQ12345** [ucloud/uai-sdk#44]
我在执行打包命令:
sudo python tf_tool.py pack --public_key=XXX
--private_key=xxx --code_path=./code/ --mainfile_path=mnist_summary.py --uhub_username=xx --uhub_password=xx  --uhub_registry=lmq_mnist_summary --uhub_imagename=tf-mnist-train --internal_uhub=false --ai_arch_v=tensorflow-1.1.0  --test_data_path=/data/test/data --test_output_path=/data/test/output --train_params="max_step=2000"
出现如下的错误：
Traceback (most recent call last):
  File "/home/user/LMQ/Ucloud/test_minist_summary/mnist/tf_tool.py", line 52, in <module>
    pack_op.cmd_run(cmd_args)
  File "build/bdist.linux-x86_64/egg/uaitrain/operation/pack_docker_image/base_pack_op.py", line 358, in cmd_run
  File "build/bdist.linux-x86_64/egg/uaitrain/operation/pack_docker_image/base_pack_op.py", line 199, in _translate_pkg_to_id
KeyError: 'DataSet'

**Comment by classicsong** [comment]
后端近期刚好更新，可以再试一下
如果不行可以找ucloud的技术支持来引导
